[package]
name = "parkour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = "0.14.0"
serde = { version = "1.0.147", features = ["derive"] }
